filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - drop_event:
          when:
            not:
              contains:
                container.name: ["notification-service", "posts-service", "user-service", "connection-service", "api-gateway", "discovery-server"]

  - type: log
    paths:
      - "/var/log/api-gateway/*.log"
      - "/var/log/posts-service/*.log"
      - "/var/log/user-service/*.log"
      - "/var/log/connection-service/*.log"
      - "/var/log/notification-service/*.log"
      - "/var/log/discovery-server/*.log"
    fields:
      log_type: application
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded


