apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-gateway-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /actuator/health
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: kafka-ui-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /kafka-ui/actuator/health
  customRequestHeaders:
    headers:
    - "X-Forwarded-Prefix:/kafka-ui"
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: zipkin-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: kibana-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /api/status