apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: abhaykumar255/professional-system_notification-service
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: notificationsDB
            - name: DB_SERVICE
              value: notifications-db
          resources:
            limits:
              memory: 400Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 50m
          ports:
            - containerPort: 9040

      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 80
      targetPort: 9040